import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { logger } from "../utils/logger.js";

interface SchemaColumn {
  name: string;
  [key: string]: unknown;
}

interface SchemaTable {
  name: string;
  description: string;
  columns: SchemaColumn[];
  constraints?: string[];
}

interface SchemaModule {
  memoGrafterExtensions: unknown;
  memoGrafterIndexes: unknown;
  memoGrafterTables: SchemaTable[];
}

export interface InitResult {
  generated: string[];
  created: string[];
  skipped: string[];
  updated: string[];
}

export async function runInit(cwd = process.cwd()): Promise<InitResult> {
  const result: InitResult = {
    generated: [],
    created: [],
    skipped: [],
    updated: [],
  };

  const memoGrafterDir = path.join(cwd, "src", "memo-grafter");
  mkdirSync(memoGrafterDir, { recursive: true });

  writeFileSync(path.join(memoGrafterDir, "mg-schema.ts"), await renderMgSchema(), "utf8");
  result.generated.push("src/memo-grafter/mg-schema.ts");

  writeIfMissing(path.join(memoGrafterDir, "schema.ts"), renderSchemaTs(), "src/memo-grafter/schema.ts", result);
  writeIfMissing(path.join(memoGrafterDir, "mg.config.ts"), renderConfigTs(), "src/memo-grafter/mg.config.ts", result);
  ensureEnvExample(cwd, result);

  logger.info("MemoGrafter project files initialized");
  for (const file of result.generated) logger.success(`${file} regenerated`);
  for (const file of result.created) logger.success(`${file} created`);
  for (const file of result.updated) logger.success(`${file} updated`);
  for (const file of result.skipped) logger.info(`- ${file} already exists, skipped`);

  return result;
}

function writeIfMissing(filePath: string, content: string, label: string, result: InitResult): void {
  if (existsSync(filePath)) {
    result.skipped.push(label);
    return;
  }

  writeFileSync(filePath, content, "utf8");
  result.created.push(label);
}

function ensureEnvExample(cwd: string, result: InitResult): void {
  const envExamplePath = path.join(cwd, ".env.example");
  const databaseLine = "DATABASE_URL=postgres://user:password@localhost:5432/memo_grafter";

  if (!existsSync(envExamplePath)) {
    writeFileSync(envExamplePath, `${databaseLine}\n`, "utf8");
    result.created.push(".env.example");
    return;
  }

  const existing = readFileSync(envExamplePath, "utf8");
  if (/^DATABASE_URL=/m.test(existing)) {
    result.skipped.push(".env.example DATABASE_URL");
    return;
  }

  const next = existing.endsWith("\n")
    ? `${existing}${databaseLine}\n`
    : `${existing}\n${databaseLine}\n`;
  writeFileSync(envExamplePath, next, "utf8");
  result.updated.push(".env.example");
}

async function renderMgSchema(): Promise<string> {
  const schema = await loadSchemaModule();
  const tableBlocks = schema.memoGrafterTables.map((table: SchemaTable) => {
    const columns = table.columns.map((column: SchemaColumn) => `      ${column.name}: ${JSON.stringify(column)},`).join("\n");
    const constraints = table.constraints
      ? `,\n    constraints: ${JSON.stringify(table.constraints)}`
      : "";
    return `  ${table.name}: {
    name: "${table.name}",
    description: "${table.description}",
    columns: {
${columns}
    }${constraints}
  },`;
  }).join("\n");

  return `// Auto-generated by memo-grafter init.
// Do not edit this file manually. Re-run \`npx memo-grafter init\` to regenerate it.

export const memoGrafterExtensions = ${JSON.stringify(schema.memoGrafterExtensions, null, 2)} as const;

export const memoGrafterTables = {
${tableBlocks}
} as const;

export const memoGrafterIndexes = ${JSON.stringify(schema.memoGrafterIndexes, null, 2)} as const;
`;
}

async function loadSchemaModule(): Promise<SchemaModule> {
  const packageName = "memo-grafter/schema";
  return await import(packageName) as SchemaModule;
}

function renderSchemaTs(): string {
  return `// Your application schema entrypoint.
//
// MemoGrafter owns and regenerates mg-schema.ts.
// This file is user-owned and will not be overwritten.
//
// Today, \`memo-grafter migrate\` manages only MemoGrafter \`mg_*\` tables.
// If you use Prisma, keep app models in prisma/schema.prisma.
// If you use another migration tool, keep using it for app tables.

export * from "./mg-schema.js";

/*
Example app table SQL for your own migration tool:

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
*/
`;
}

function renderConfigTs(): string {
  return `declare const process: {
  env: {
    DATABASE_URL?: string;
  };
};

export default {
  db: {
    connectionString: process.env.DATABASE_URL,
  },
};
`;
}
