import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { logger } from "../utils/logger.js";

interface SchemaColumn {
  name: string;
  [key: string]: unknown;
}

interface SchemaTable {
  name: string;
  description: string;
  columns: SchemaColumn[];
  constraints?: string[];
}

interface SchemaModule {
  memoGrafterExtensions: unknown;
  memoGrafterIndexes: unknown;
  memoGrafterTables: SchemaTable[];
}

export interface InitResult {
  generated: string[];
  created: string[];
  skipped: string[];
  updated: string[];
}

export async function runInit(cwd = process.cwd()): Promise<InitResult> {
  const result: InitResult = {
    generated: [],
    created: [],
    skipped: [],
    updated: [],
  };

  const memoGrafterDir = path.join(cwd, "src", "memo-grafter");
  mkdirSync(memoGrafterDir, { recursive: true });

  writeFileSync(path.join(memoGrafterDir, "mg-schema.ts"), await renderMgSchema(), "utf8");
  result.generated.push("src/memo-grafter/mg-schema.ts");

  writeIfMissing(path.join(memoGrafterDir, "mg.config.ts"), renderConfigTs(), "src/memo-grafter/mg.config.ts", result);
  ensureEnvExample(cwd, result);

  logger.info("MemoGrafter project files initialized");
  for (const file of result.generated) logger.success(`${file} regenerated`);
  for (const file of result.created) logger.success(`${file} created`);
  for (const file of result.updated) logger.success(`${file} updated`);
  for (const file of result.skipped) logger.info(`- ${file} already exists, skipped`);

  return result;
}

function writeIfMissing(filePath: string, content: string, label: string, result: InitResult): void {
  if (existsSync(filePath)) {
    result.skipped.push(label);
    return;
  }

  writeFileSync(filePath, content, "utf8");
  result.created.push(label);
}

function ensureEnvExample(cwd: string, result: InitResult): void {
  const envExamplePath = path.join(cwd, ".env.example");
  const requiredLines = [
    "DATABASE_URL=postgres://user:password@localhost:5432/memo_grafter",
    "OPENAI_API_KEY=",
    "MEMO_GRAFTER_EMBEDDING_MODEL=text-embedding-3-small",
  ];

  if (!existsSync(envExamplePath)) {
    writeFileSync(envExamplePath, `${requiredLines.join("\n")}\n`, "utf8");
    result.created.push(".env.example");
    return;
  }

  const existing = readFileSync(envExamplePath, "utf8");
  const missingLines = requiredLines.filter((line) => {
    const key = line.slice(0, line.indexOf("="));
    return !new RegExp(`^${escapeRegExp(key)}=`, "m").test(existing);
  });

  if (missingLines.length === 0) {
    result.skipped.push(".env.example DATABASE_URL");
    return;
  }

  const next = existing.endsWith("\n")
    ? `${existing}${missingLines.join("\n")}\n`
    : `${existing}\n${missingLines.join("\n")}\n`;
  writeFileSync(envExamplePath, next, "utf8");
  result.updated.push(".env.example");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

async function renderMgSchema(): Promise<string> {
  const schema = await loadSchemaModule();
  const tableBlocks = schema.memoGrafterTables.map((table: SchemaTable) => {
    const columns = table.columns.map(renderSchemaColumn).join("\n");
    const constraints = table.constraints
      ? `,\n    constraints: ${JSON.stringify(table.constraints)}`
      : "";
    return `  ${renderPropertyName(table.name)}: {
    name: ${JSON.stringify(table.name)},
    description: ${JSON.stringify(table.description)},
    columns: {
${columns}
    }${constraints}
  },`;
  }).join("\n");

  return `// Auto-generated by memo-grafter init.
// Do not edit this file manually. Re-run \`npx memo-grafter init\` to regenerate it.

export const memoGrafterExtensions = ${JSON.stringify(schema.memoGrafterExtensions, null, 2)} as const;

export const memoGrafterTables = {
${tableBlocks}
} as const;

export const memoGrafterIndexes = ${JSON.stringify(schema.memoGrafterIndexes, null, 2)} as const;
`;
}

function renderSchemaColumn(column: SchemaColumn): string {
  const properties = Object.entries(column)
    .map(([name, value]) => `        ${renderPropertyName(name)}: ${JSON.stringify(value)},`)
    .join("\n");

  return `      ${renderPropertyName(column.name)}: {
${properties}
      },`;
}

function renderPropertyName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

async function loadSchemaModule(): Promise<SchemaModule> {
  const packageName = "memo-grafter/schema";
  return await import(packageName) as SchemaModule;
}

function renderConfigTs(): string {
  return `declare const process: {
  env: {
    DATABASE_URL?: string;
    OPENAI_API_KEY?: string;
    MEMO_GRAFTER_EMBEDDING_MODEL?: string;
  };
};

const embeddingModel = process.env.MEMO_GRAFTER_EMBEDDING_MODEL ?? "text-embedding-3-small";

export default {
  db: {
    connectionString: process.env.DATABASE_URL,
  },
  // Prompt Preview uses this embedder to run graft/recall preview from Studio.
  // Set OPENAI_API_KEY in your environment or replace this object with your own embedder.
  embedder: process.env.OPENAI_API_KEY
    ? {
      async embed(text: string): Promise<number[]> {
        const response = await fetch("https://api.openai.com/v1/embeddings", {
          method: "POST",
          headers: {
            "content-type": "application/json",
            authorization: \`Bearer \${process.env.OPENAI_API_KEY}\`,
          },
          body: JSON.stringify({
            model: embeddingModel,
            input: text,
          }),
        });

        if (!response.ok) {
          throw new Error(\`OpenAI embeddings request failed: \${response.status} \${await response.text()}\`);
        }

        const body = await response.json() as { data?: Array<{ embedding?: number[] }> };
        const embedding = body.data?.[0]?.embedding;
        if (!embedding) throw new Error("OpenAI embeddings response did not include an embedding.");
        return embedding;
      },
    }
    : undefined,
};
`;
}
