import type { Message } from "../core/types.js";
import { normalizeText } from "../utils/text/normalizeText.js";

export function buildSegmentExtractionPrompt(messages: Message[], labelHint?: string): string {
  const messageContent = messages
    .map((message, index) => `Message ${index + 1}:\n[${message.role}] ${normalizeText(message.content) ?? message.content}`)
    .join("\n\n");

  return [
    "Analyze this conversation segment and extract structured memory for a future chatbot.",
    "",
    "Return a single valid JSON object and nothing else. Do not include markdown fences, backticks, a preamble, comments, or trailing text.",
    "",
    "The JSON object must match this exact schema:",
    "{",
    '  "label": "3-6 word topic label",',
    '  "user_intent": "two-three sentences describing what the user was trying to achieve",',
    '  "outcome": "one-two sentences describing what was concluded, decided, or provided",',
    '  "open": "one sentence describing any unresolved question, or null",',
    '  "memories": [',
    "    {",
    '      "memory_type": "fact | insight | question | task | reference",',
    '      "subject": "person, team, project, system, tool, or concept the memory is about",',
    '      "predicate": "short relationship or attribute phrase",',
    '      "value": "one sentence maximum, self-contained and meaningful without surrounding context",',
    '      "confidence": 0.95',
    "    }",
    "  ]",
    "}",
    "",
    "Memory type definitions:",
    "- fact: explicit assertion, preference, decision, or constraint directly stated",
    "- insight: synthesized or implied understanding, not directly stated",
    "- question: unresolved or open question raised in the conversation",
    "- task: something actionable, a to-do, or next step",
    "- reference: an external tool, service, library, or resource being discussed",
    "",
    "Confidence scoring:",
    "- Explicit direct statement: 0.9-1.0",
    "- Implied or inferred: 0.5-0.8",
    "- Uncertain or speculative: below 0.5",
    "",
    "Rules:",
    "- The value field must be one sentence maximum.",
    "- The value field must be self-contained and meaningful without surrounding context.",
    "- When a statement explicitly corrects, replaces, or updates an earlier fact, preserve that update cue in the value, such as actually, now, changed to, or instead.",
    "- If no memories are extractable from the segment, return an empty memories array.",
    "- Use null for open when there is no unresolved question or follow-up.",
    ...(labelHint
      ? [
        `- Use "${labelHint}" as a hint when choosing the topic label. Keep the label accurate to the content.`,
      ]
      : []),
    "",
    "Example segment:",
    "Message 1:",
    "[user] I prefer PostgreSQL over MongoDB for this billing service because we need relational integrity. Should connection pooling live in the app or infra layer?",
    "",
    "Message 2:",
    "[assistant] PostgreSQL is a good fit for the billing service. Connection pooling can work in either place; the team should decide based on deployment ownership.",
    "",
    "Expected JSON output:",
    "{",
    '  "label": "Billing Database Choice",',
    '  "user_intent": "The user wanted to confirm a database preference for a billing service and clarify where connection pooling should be handled. They emphasized the need for relational integrity.",',
    '  "outcome": "PostgreSQL was treated as a good fit for the billing service. The connection pooling decision was left dependent on deployment ownership.",',
    '  "open": "The team still needs to decide whether connection pooling belongs in the app or infra layer.",',
    '  "memories": [',
    "    {",
    '      "memory_type": "fact",',
    '      "subject": "user",',
    '      "predicate": "prefers database",',
    '      "value": "PostgreSQL over MongoDB for the billing service because it needs relational integrity.",',
    '      "confidence": 0.95',
    "    },",
    "    {",
    '      "memory_type": "question",',
    '      "subject": "team",',
    '      "predicate": "undecided on",',
    '      "value": "whether connection pooling should live in the app or infra layer.",',
    '      "confidence": 0.8',
    "    }",
    "  ]",
    "}",
    "",
    "Conversation segment:",
    messageContent,
  ].join("\n");
}
